### ISSUE TITLE
[Bug] helm install cannot take sa for FE/BE deployment

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#61] opened 2023-03-10 06:47 UTC
**Version: 1.3.5**

**Problems**
It seems that it tries to create a sa instead of accepting an existing sa.

**Reproduce Steps:**
1) create a sa to a namespace e.g. `celostar`
2) set these two fields with the same sa name in values.yaml : `starrocksFESpec.serviceAccount` `starrocksFESpec.serviceAccount`
3) helm install with the values.yaml will get this error:
> Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "celostar" in namespace "celostar" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "starrocks"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "celostar"

**Comment by dengliu** [comment] 2023-03-10 06:47
@kevincai @shileifu

**Comment by kevincai** [comment] 2023-03-10 07:18
Find the root cause
```yaml
  1 # Default values for kube-starrocks.
  2 # This is a YAML-formatted file.
  3 # Declare variables to be passed into your templates.
  4 kube-starrocks:
  5   global:
  6     rbac:
  7       create: true
  8 
  9   # deploy operator in special namespace.
 10   nameOverride: celostar
 11   starrocksOperator:
 12     # provide a name for operator deployment.
 13     enabled: true
 14     serviceAccountName: ""
 15     namespaceOverride: ""
```

In `values.yaml` file, if line 14 `serviceAccountName` is not provided, it will use `nameOverride` in line 10 as the operator's service account, that is `celostar`.  And accidentally you created a manual managed service account with the same name, helm chart takes it as the operator's service account and report errors.

Try to FE/BE's service account a different name, or provide operator's service account a name other than the default `nameOverride`. It should be fine.

**Comment by dengliu** [comment] 2023-03-10 07:33
ln 10:  `nameOverride` is very confusing.
and the comment in `ln 9` makes it every more confusing as you have `ln 15: serviceAccountName`.
Does it make sense to make it  field under `starrocksOperator.nameOverride`  and adapt comments?

**Comment by kevincai** [comment] 2023-03-10 07:36
`nameOverride` is used as default value for multiple places. Will think about better alternatives.

Meanwhile, would you please confirm that this solves your problem?

**Comment by dengliu** [comment] 2023-03-11 06:04
![image](https://user-images.githubusercontent.com/5108773/224467891-96e43b94-09f2-44a0-a0d9-c41e5f4cf930.png)
I was able to solve this issue by explicitly set a name `starrocksOperator.serviceAccountName: sr-operator` that is different from the sa that I want to pass to fe/be.

the Ln 10: `nameOverride` , seems to be used as a prefix for other components. It would be better to think about a better description of this or just refactor it in another way.

e.g. when I set it to `celostar` I got:
-  service name: `celostar-fe-service`
- pod name: `celostar-be-[0,1,2,3..]`
- pod name: `celostar-fe-[0,1,2,3..]`

**Comment by kevincai** [comment] 2023-03-11 14:08
Thanks for the confirmation. we will make the `nameOverride` a much accurate description, in the meanwhile, will remove the `serviceAccountName` setting for the operator, it is not necessary to let user to give a name.

close this issue for now.

**Closed by kevincai** 2023-03-11 14:08 UTC
